mainsite/urls.py
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
"""

from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name = 'index.html'), name = 'home'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls'))

]

posts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.views.generic.base import TemplateView
from . import views

app_name = 'posts'

urlpatterns = [
    path('list/', views.p_list, name = 'list'),
    path('create/', views.p_create, name = 'create'),
    path('<int:post_id>/delete/', views.p_delete, name = 'delete'),
    path('<int:post_id>/edit/', views.p_edit, name = 'edit'),
    path('<int:post_id>/detail/', views.p_detail, name = 'detail')
]

posts/models.py
from django.db import models
#from datetime import timedelta
from django.utils import timezone

class Post(models.Model):
    author = models.CharField('작성자 / Writer',max_length= 20,blank=True)
    contents = models.TextField('내용 / Contents',max_length=1000,blank=True)
    id = models.AutoField

    def __str__(self):
        return self.contents

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField('작성자',max_length= 20,blank=True)
    created_date = models.DateField('Date',max_length=10,default=timezone.now,blank=True)
    text = models.TextField('Comments',max_length=1000,blank=True)

    def __str__(self):
        return self.created_date

posts/views.py
from django.shortcuts import render, redirect, get_object_or_404

# Create your views here.
from .models import Post, Comment
from .form import PostForm

def p_list(request):
    my_list = Post.objects.all().order_by('-id')
    context = {'posts':my_list}
    return render(request,'list.html', context)

def p_create(request):
    if request.method == "POST":
        post_form = PostForm(request.POST)

        if post_form.is_valid():
            post_form.save()
            return redirect('posts:list')

    else:
        post_form = PostForm()

    return render(request, 'create.html', {'post_form':post_form})

def p_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()

    return redirect('posts:list')

def p_edit(request, post_id):
    post = get_object_or_404(Post, pk = post_id)

    if request.method == "POST":
        post_form = PostForm(request.POST,instance=post)

        if post_form.is_valid():
            post_form.save()
            return redirect('posts:list')

    else:
        post_form = PostForm(instance=post)

    return render(request, 'create.html', {'post_form':post_form})

def p_detail(request, post_id):
    detail = Post.objects.get(pk = post_id)
    comment = Comment.objects.get(post=post_id)

    return render(request, 'detail.html', {'detail': detail, 'comment': comment})

mainsite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Publisher</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

</head>
<body>
    {% block container %}
    {% endblock %}
</body>
</html>

mainsite/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>게시판 / Bulletin Board</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/css/bootstrap.min.css" integrity="sha384-VCmXjywReHh4PwowAiWNagnWcLhlEJLA5buUprzK8rxFgeH0kww/aWY76TfkUoSX" crossorigin="anonymous">

    <!-- Favicons -->
    <meta name="theme-color" content="#563d7c">

    <!-- Custom styles for this template -->
    <link href="/static/css/cover.css" rel="stylesheet">
</head>

<body class="text-center">
  <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand"></h3>
    </div>
  </header>

  <main role="main" class="inner cover">
    <h1 class="cover-heading">게시판에 오신것을 환영합니다 / Welcome to the bulletin board</h1>
    <p class="lead">아래의 버튼을 클릭해 게시판에 접속하세요 / Click the button below to access the bulletin board</p>
    <p class="lead">
    <a href="/posts/list" class="btn btn-lg btn-secondary">게시판 / Continue</a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Developed by: <a href='https://postgrethon.wordpress.com'>Postgrethon Software House</a></p>
    </div>
  </footer>
  </div>
</body>
</html>

posts/templates/create.html
{% extends 'base.html'%}
{% load bootstrap4 %}
{% block container %}
    <div class="container">
        <h1>새글 작성 / Create a new post</h1>
        <form method="post">
            {%csrf_token%}
            {%bootstrap_form post_form %}

            <a href='http://publishsys.pythonanywhere.com/posts/list/'>Back to Home</a>
            <button type="submit" class="btn btn-info">등록 / Enrollment</button>
        </form>
    </div>
{%endblock%}

posts/templates/detail.html
{% extends 'base.html'%}
{% block container %}
<script src = "/static/js/post.js"></script>
    <div class="container">
        <h1>글내용확인 / Check the content of the article</h1>
        <h4>글번호 / Article no: {{detail.id}}</h4>>
        <h4>작성자 / Writer: {{detail.author}}</h4>
        <h4>내용 / Contents: {{detail.contents}}</h4>

        <hr>
        <button class="btn btn-info" onclick="new_post()">새 댓글 작성 / Create a new comment</button>
        <div class = "m-2"></div>

        <table class="table table-hover">
            <thead class = "thead-light">
                <tr>
                    <th scope="col">Date</th>
                    <th scope="col">Writer</th>
                    <th scope="col">Comment</th>
                    <th scope="col">수정 / Edit</th>
                    <th scope="col">삭제 / Delete</th>
                </tr>
            </thead>

            <tbody>
                {% for comment in posts.comments.all %}
                <tr>
                    <th scope="row">{{comment.post}}</th>
                    <td>{{comment.created_date}}</td>
                    <td>{{comment.author}}</td>
                    <td>{{comment.text}}</td>
                    <td>
                        <a href = "{% url 'posts:edit' post.id %}" class="btn btn-secondary">수정 / Edit</a>
                    </td>
                    <td>
                        <a href = "{% url 'posts:delete' post.id %}" class="btn btn-warning">삭제 / Delete</a>
                    </td>
                </tr>

                <div class="comment">
                    <div class="date">{{ comment.created_date }}</div>
                    <strong>{{ comment.author }}</strong>
                    <p>{{ comment.text|linebreaks }}</p>
                </div>

                {% empty %}
                <p>댓글이 없습니다 / No Comments</p>
                {% endfor %}
            </tbody>
        </table>
    </div>
{%endblock%}

posts/templates/list.html
{% extends 'base.html'%}
{% block container %}
<script src = "/static/js/post.js"></script>
    <div class="container">
        <h1>게시판 / Bulletin Board</h1>
        <button class="btn btn-info" onclick="new_post()">새글 작성 / Create a new post</button>
        <div class = "m-1"></div>

        <table class="table table-hover">
            <thead class = "thead-light">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">작성자 / Writer</th>
                    <th scope="col">내용 / Contents</th>
                    <th scope="col">수정 / Edit</th>
                    <th scope="col">삭제 / Delete</th>
                </tr>
            </thead>

            <tbody>
            {%for post in posts %}
                <tr>
                    <th scope="row">{{post.id}}</th>
                    <td>{{post.author}}</td>
                    <td>{{post.contents}}</td>
                    <td>
                        <a href = "{% url 'posts:edit' post.id %}" class="btn btn-secondary">수정 / Edit</a>
                    </td>
                    <td>
                        <a href = "{% url 'posts:delete' post.id %}" class="btn btn-warning">삭제 / Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{%endblock%}